"""
Django settings for progress_tracker project.

Generated by 'django-admin startproject' using Django 5.2.8.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/


# SECURITY WARNING: keep the secret key used in production secret!
import environ
import os
env = environ.Env()
# Read .env file from the same directory as settings.py
environ.Env.read_env(os.path.join(os.path.dirname(__file__), '.env'))
SECRET_KEY = env('SECRET_KEY')

ENVIRONMENT = env("ENVIRONMENT", default="local")  # local | prod
DEBUG = env.bool("DEBUG", default=(ENVIRONMENT == "local"))


# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env.bool("DEBUG", default=False)

ALLOWED_HOSTS = ['vismatrix.space','www.vismatrix.space','3.229.115.6','localhost','127.0.0.1']


# Application definition
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    
    # Allauth requirements
    'django.contrib.sites',
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    'allauth.socialaccount.providers.google',
    
    # Your app (use the config class)
    'tracker.apps.TrackerConfig',  # Changed from just 'tracker'
    'widget_tweaks',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'tracker.timezone_middleware.TimezoneMiddleware',  # Add timezone middleware after auth
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'allauth.account.middleware.AccountMiddleware',
    'tracker.middleware.SaveMessagesMiddleware',  # Save Django messages to database
]

# Site configuration
SITE_ID = 1
# Authentication backends
AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',
    'allauth.account.auth_backends.AuthenticationBackend',
]

# Allauth settings
# ACCOUNT_EMAIL_REQUIRED = False
# ACCOUNT_USERNAME_REQUIRED = True
# ACCOUNT_AUTHENTICATION_METHOD = 'username_email'
ACCOUNT_EMAIL_VERIFICATION = 'none'  # Disable email verification

# Custom adapter for Pro subscription handling
ACCOUNT_ADAPTER = 'tracker.adapter.ProSubscriptionAdapter'

# Updated Allauth settings for newer versions
ACCOUNT_LOGIN_METHODS = {'username', 'email'}
ACCOUNT_SIGNUP_FIELDS = ['username*', 'email', 'password1*', 'password2*']

# Login settings
LOGIN_URL = '/accounts/login/'  # allauth login URL
LOGIN_REDIRECT_URL = '/dashboard/'  # Redirect to dashboard after login
ACCOUNT_LOGOUT_REDIRECT_URL = '/'  # Redirect to landing page after logout
ACCOUNT_AUTHENTICATED_LOGIN_REDIRECTS = True

SOCIALACCOUNT_AUTO_SIGNUP = True
SOCIALACCOUNT_STORE_TOKENS = True
ACCOUNT_MERGE_ENABLED = False  # Prevents 3rdparty redirect
SOCIALACCOUNT_LOGIN_ON_GET = True


# Social account settings
SOCIALACCOUNT_PROVIDERS = {
    'google': {
        'SCOPE': [
            'profile',
            'email',
        ],
        'AUTH_PARAMS': {
            'access_type': 'online',
        }
    }
}

SOCIALACCOUNT_EMAIL_VERIFICATION = 'optional'


ROOT_URLCONF = "progress_tracker.urls"

import os
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'tracker', 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'django.template.context_processors.csrf',
                # Your new processor
                'tracker.context_processors.pending_friend_requests_count',
                'tracker.context_processors.user_timezone',  # Add timezone context
                'tracker.context_processors.user_subscription',  # Add subscription context
            ],
        },
    },
]


WSGI_APPLICATION = "progress_tracker.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": os.path.join(BASE_DIR, "db.sqlite3"),
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/


# Static files (CSS, JavaScript, Images)
STATIC_URL = '/static/'
STATIC_ROOT = env("STATIC_ROOT", default=os.path.join(BASE_DIR, "staticfiles"))


# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

STATICFILES_DIRS = []


DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"


# --- Google Calendar API Configuration ---
GOOGLE_CLIENT_ID = env('GOOGLE_CLIENT_ID', default='')
GOOGLE_CLIENT_SECRET = env('GOOGLE_CLIENT_SECRET', default='')
GOOGLE_REDIRECT_URI = env('GOOGLE_REDIRECT_URI', default='http://127.0.0.1:8000/calendar/oauth2callback/')


# --- GeoIP Configuration ---
# Path to MaxMind GeoLite2 database for IP geolocation
GEOIP_PATH = os.path.join(BASE_DIR, 'geoip', 'GeoLite2-City.mmdb')


# --- Same-domain Next.js + Django (reverse proxy) ---
if ENVIRONMENT == "prod":
    CSRF_TRUSTED_ORIGINS = ["https://vismatrix.space", "https://www.vismatrix.space"]

    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SESSION_COOKIE_SAMESITE = "Lax"
    CSRF_COOKIE_SAMESITE = "Lax"

    SESSION_COOKIE_DOMAIN = ".vismatrix.space"
    CSRF_COOKIE_DOMAIN = ".vismatrix.space"

    SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")
    SECURE_SSL_REDIRECT = True
else:
    # Local dev
    CSRF_TRUSTED_ORIGINS = ["http://localhost", "http://127.0.0.1"]
    SESSION_COOKIE_SECURE = False
    CSRF_COOKIE_SECURE = False


# --- End Same-domain Next.js + Django (reverse proxy) ---


# --- Google AdSense Configuration ---
# Enable/disable ads globally (set to False during development/testing)
GOOGLE_ADSENSE_ENABLED = env.bool('GOOGLE_ADSENSE_ENABLED', default=False)

# Your AdSense Publisher ID (get this from AdSense dashboard)
# Format: ca-pub-XXXXXXXXXXXXXXXX
GOOGLE_ADSENSE_CLIENT_ID = env('GOOGLE_ADSENSE_CLIENT_ID', default='ca-pub-7653466283203958')

# Ad unit slots (get these from AdSense dashboard after creating ad units)
# Each ad unit has a unique slot ID
GOOGLE_ADS_SLOTS = {
    'header_banner': env('GOOGLE_ADS_HEADER_SLOT', default=''),      # Top banner (728x90 or responsive)
    'sidebar': env('GOOGLE_ADS_SIDEBAR_SLOT', default=''),           # Sidebar ad (300x250)
    'in_content': env('GOOGLE_ADS_CONTENT_SLOT', default=''),        # In-content ad (336x280)
    'mobile_banner': env('GOOGLE_ADS_MOBILE_SLOT', default=''),      # Mobile banner (320x50)
}
# --- End Google AdSense Configuration ---


# --- Stripe Payment Configuration ---
# Get these from https://dashboard.stripe.com/apikeys
STRIPE_PUBLISHABLE_KEY = env('STRIPE_PUBLISHABLE_KEY', default='')
STRIPE_SECRET_KEY = env('STRIPE_SECRET_KEY', default='')

# Webhook secret for verifying Stripe webhook signatures
# Get this from Stripe Dashboard > Developers > Webhooks
STRIPE_WEBHOOK_SECRET = env('STRIPE_WEBHOOK_SECRET', default='')

# Pro subscription pricing
PRO_SUBSCRIPTION_PRICE = 20.00  # USD per month
# --- End Stripe Payment Configuration ---

